av_ingest_meme_stonks:
  description: 'dags for extracting 5 tickers'
  source: 'av-daily'
  start: '2021-01-01' # start is for the alpha vantage api's start
  start_date: '2021-01-01'
  schedule: '0 * * * *'
  tickers:
    - GME
    - AMC
    - CLOV
    - BBBY
    - SNDL

av_ingest_3x_fin_etf:
  description: 'dags for extracting 5 tickers'
  source: 'av-daily'
  start: '2021-01-01'
  start_date: '2021-01-01'
  schedule: '1 * * * *'
  tickers:
    - FAS
    - FAZ

av_ingest_3x_qqq_etf:
  description: 'dags for extracting 5 tickers'
  source: 'av-daily'
  start: '2021-01-01'
  start_date: '2021-01-01'
  schedule: '2 * * * *'
  tickers:
    - SQQQ
    - TQQQ

av_ingest_3x_cn_etf:
  description: 'dags for extracting 5 tickers'
  source: 'av-daily'
  start: '2021-01-01'
  start_date: '2021-01-01'
  schedule: '3 * * * *'
  tickers:
    - YINN
    - YANG

av_ingest_3x_vix:
  description: 'dags for extracting 5 tickers'
  source: 'av-daily'
  start: '2021-01-01'
  start_date: '2021-01-01'
  schedule: '4 * * * *'
  tickers:
    - UVXY
    - SVXY