yahoo_most_active_200:
  description: 'scrape and ingest yahoo most active 200'
  start_date: '2021-01-01'
  schedule: '0 * * * *'
  url:
    https://finance.yahoo.com/most-active?offset=0&count=200
deeptendies_meme_stonks_tracker:
  description: 'deeptendies_meme_stonks_tracker'
  start_date: '2021-01-01'
  schedule: '0 * * * *'
  url:
    https://docs.google.com/spreadsheets/d/e/2PACX-1vRlC0BS7OwGHLvtKU6BangSn6Q5PYJ7hOGlZ_ml4Bdf5DQnRTEjzrTMFBOtfHqdp0wEGqdOVeq0TwUX/pubhtml?gid=909584410&single=true
bear_bull_etfs_tracker:
  description: 'bear_bull_etfs_tracker'
  start_date: '2021-01-01'
  schedule: '0 * * * *'
  url:
    https://docs.google.com/spreadsheets/u/1/d/e/2PACX-1vS5d-FwSX_r13cli9JLNldCtUZWl3WYam10P9tVA50WjobUl9DoAKscLxPpLzvg2aBxiuN9kwXFBgdW/pubhtml?gid=886270006&single=true